name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check format
      run: cargo build --verbose
    - name: Check clippy
      run: cargo clippy --verbose -- -D clippy::all
    - name: Run unit tests
      run: cargo test --verbose --all
    - name: Run client integration tests
      run: cargo xtask test-js
