name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check dashboard frontend formatting
      uses: creyD/prettier_action@v4.2
      with:
        dry: true
        prettier_options: --check amqp_dashboard/assets/* --ignore-path .gitignore
    - name: Build
      run: cargo build --verbose
    - name: Run clippy -D clippy::all
      run: cargo clippy --verbose -- -D clippy::all
    - name: Check format
      run: cargo +nightly fmt --verbose --all -- --check
    - name: Run tests
      run: cargo test --verbose --all
    - name: Run client integration tests
      run: cargo xtask test-js
